name: schema-check

on:
  push:
    paths:
      - "schema.json"
      - "examples/**.json"
      - ".github/workflows/validate.yml"
  pull_request:
    paths:
      - "schema.json"
      - "examples/**.json"

jobs:
  ajv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install AJV CLI
        run: npm install -g ajv-cli ajv-formats

 #     - name: Validate schema against Draft-07 meta-schema
 #       run: |
 #         ajv validate \
 #           -s 'http://json-schema.org/draft-07/schema#' \
 #           -d agent_profile_v0.1.json

      - name: Validate all example agents
        run: |
          ajv validate \
            -c ajv-formats \
            -s schema.json \
            -d "examples/*.json"
